name: Build LKM for KernelSU
on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/build-lkm.yml"
  pull_request:
    branches: ["master"]
    paths:
      - ".github/workflows/build-lkm.yml"
  workflow_call:
  workflow_dispatch:
    inputs:
      KSUBRANCH:
        type: string
        description: "KernelSU branch"
        default: 'main'
        required: true
jobs:
  build-lkm:
    strategy:
      matrix:
        include:
          - version: "android12-5.10"
            sub_level: 236
            os_patch_level: 2025-05
          - version: "android13-5.10"
            sub_level: 234
            os_patch_level: 2025-03
          - version: "android13-5.15"
            sub_level: 178
            os_patch_level: 2025-03
          - version: "android14-5.15"
            sub_level: 178
            os_patch_level: 2025-03
          - version: "android14-6.1"
            sub_level: 134
            os_patch_level: 2025-05
          - version: "android15-6.6"
            sub_level: 87
            os_patch_level: 2025-05
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: ${{ matrix.version }}
      version_name: ${{ matrix.version }}.${{ matrix.sub_level }}
      tag: ${{ matrix.version }}-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      ksu_branch: ${{ inputs.KSUBRANCH }}
