name: Build LKM for KernelSU
on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/build-lkm.yml"
  pull_request:
    branches: ["master"]
    paths:
      - ".github/workflows/build-lkm.yml"
  workflow_call:
  workflow_dispatch:
    inputs:
      KSUBRANCH:
        type: string
        description: "KernelSU branch"
        default: 'main'
        required: true
jobs:
  build-lkm:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: "android12-5.10"
            sub_level: 240
            os_patch_level: 2025-09
          - version: "android13-5.10"
            sub_level: 238
            os_patch_level: 2025-07
          - version: "android13-5.15"
            sub_level: 189
            os_patch_level: 2025-09
          - version: "android14-5.15"
            sub_level: 185
            os_patch_level: 2025-07
          - version: "android14-6.1"
            sub_level: 145
            os_patch_level: 2025-09
          - version: "android15-6.6"
            sub_level: 98
            os_patch_level: 2025-09
          - version: "android16-6.12"
            sub_level: 38
            os_patch_level: 2025-09
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: ${{ matrix.version }}
      version_name: ${{ matrix.version }}.${{ matrix.sub_level }}
      tag: ${{ matrix.version }}-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      ksu_branch: ${{ inputs.KSUBRANCH }}
