name: Android 15 6.6

on:
  workflow_call:  # This allows this workflow to be called from another workflow

jobs:
  build-kernel-a15-6-6-kernelsu:
    strategy:
      matrix:
        include:
          #- sub_level: "30"
          #  os_patch_level: "2024-08"
          #- sub_level: "46"
          #  os_patch_level: "2024-09"
          - sub_level: "50"
            os_patch_level: "2024-10"
          - sub_level: "56"
            os_patch_level: "2024-11"
          - sub_level: "57"
            os_patch_level: "2024-12"
          - sub_level: "58"
            os_patch_level: "2025-01"
          - sub_level: "66"
            os_patch_level: "2025-02"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      version: "android15-6.6"
      version_name: "android15-6.6.${{ matrix.sub_level }}"
      tag: "android15-6.6-${{ matrix.os_patch_level }}"
      os_patch_level: ${{ matrix.os_patch_level }}
      build_lkm: false
