name: Android 13 5.15

on:
  workflow_call:  # This allows this workflow to be called from another workflow
  
jobs:
  build-kernel-a13-5-15-kernelsu:
    strategy:
      matrix:
        include:
          - sub_level: "94"
            os_patch_level: "2023-05"
          - sub_level: "123"
            os_patch_level: "2023-11"
          - sub_level: "137"
            os_patch_level: "2024-01"
          - sub_level: "144"
            os_patch_level: "2024-03"
          - sub_level: "148"
            os_patch_level: "2024-05"
          - sub_level: "149"
            os_patch_level: "2024-07"
          - sub_level: "151"
            os_patch_level: "2024-08"
          - sub_level: "167"
            os_patch_level: "2024-11"
          - sub_level: "170"
            os_patch_level: "2025-01"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      version: "android13-5.15"
      version_name: "android13-5.15.${{ matrix.sub_level }}"
      tag: "android13-5.15-${{ matrix.os_patch_level }}"
      os_patch_level: ${{ matrix.os_patch_level }}
      build_lkm: false
