name: Android 14 6.1

on:
  workflow_call:  # This allows this workflow to be called from another workflow

jobs:
  build-kernel-a14-6-1-kernelsu:
    strategy:
      matrix:
        include:
          - sub_level: "25"
            os_patch_level: "2023-10"
          - sub_level: "43"
            os_patch_level: "2023-11"
          - sub_level: "57"
            os_patch_level: "2024-01"
          - sub_level: "68"
            os_patch_level: "2024-03"
          - sub_level: "75"
            os_patch_level: "2024-05"
          - sub_level: "78"
            os_patch_level: "2024-06"
          - sub_level: "84"
            os_patch_level: "2024-07"
          - sub_level: "90"
            os_patch_level: "2024-08"
          - sub_level: "112"
            os_patch_level: "2024-11"
          - sub_level: "115"
            os_patch_level: "2024-12"
          - sub_level: "118"
            os_patch_level: "2025-01"
          - sub_level: "124"
            os_patch_level: "2025-02"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      version: "android14-6.1"
      version_name: "android14-6.1.${{ matrix.sub_level }}"
      tag: "android14-6.1-${{ matrix.os_patch_level }}"
      os_patch_level: ${{ matrix.os_patch_level }}
      build_lkm: false
