name: Android 13 5.10

on:
  workflow_call:  # This allows this workflow to be called from another workflow

jobs:
  build-kernel-a13-5-10-kernelsu:
    strategy:
      matrix:
        include:
          - sub_level: "189"
            os_patch_level: "2023-11"
          - sub_level: "198"
            os_patch_level: "2024-01"
          - sub_level: "205"
            os_patch_level: "2024-03"
          - sub_level: "209"
            os_patch_level: "2024-05"
          - sub_level: "210"
            os_patch_level: "2024-06"
          - sub_level: "214"
            os_patch_level: "2024-07"
          - sub_level: "218"
            os_patch_level: "2024-08"
          - sub_level: "223"
            os_patch_level: "2024-11"
          - sub_level: "228"
            os_patch_level: "2025-01"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      version: "android13-5.10"
      version_name: "android13-5.10.${{ matrix.sub_level }}"
      tag: "android13-5.10-${{ matrix.os_patch_level }}"
      os_patch_level: ${{ matrix.os_patch_level }}
      build_lkm: false
