name: Release LKM
on:
  workflow_dispatch:

jobs:
  build-lkm:
    uses: ./.github/workflows/build-lkm.yml
    secrets: inherit
  release:
    needs:
      - build-lkm
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Get KernelSU manifest
        id: ksu
        run: |
          git clone https://github.com/luyanci/KernelSU.git && cd KernelSU
          echo "TAGS=`git describe --tags --always`" >> $GITHUB_OUTPUT
          COMMIT_COUNT=$(git rev-list --count HEAD)
          VER=$(expr 10200 + $COMMIT_COUNT)
          echo "NUM=`echo $VER`" >> $GITHUB_OUTPUT
          echo "LAST_COMMIT=`git show-branch --no-name HEAD`" >> $GITHUB_OUTPUT
      - name: Display structure of downloaded files
        run: ls -R
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: android*-lkm/*_kernelsu.ko
          name: ${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: |
            Last KernelSU commit: ```${{ steps.ksu.outputs.LAST_COMMIT }}```
            KernelSU version: ```${{ steps.ksu.outputs.NUM }}```
            KernelSU tags: ```${{ steps.ksu.outputs.TAGS }}```
            Run-id: ```${{ github.run_id }}```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
